DEBUG 2019-04-05 21:50:26,773: 	 Executing command: 'submit'
DEBUG 2019-04-05 21:50:26,774: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
DEBUG 2019-04-05 21:50:26,794: 	 Checking credentials
DEBUG 2019-04-05 21:50:26,798: 	 Found proxy file /tmp/x509up_u104803
DEBUG 2019-04-05 21:50:26,798: 	 Getting proxy life time left
ERROR 2019-04-05 21:50:27,403: 	 Keyboard Interrupted
DEBUG 2019-04-05 21:59:00,041: 	 Executing command: 'submit'
DEBUG 2019-04-05 21:59:00,041: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
DEBUG 2019-04-05 21:59:00,054: 	 Checking credentials
DEBUG 2019-04-05 21:59:00,057: 	 Found proxy file /tmp/x509up_u104803
DEBUG 2019-04-05 21:59:00,057: 	 Getting proxy life time left
DEBUG 2019-04-05 21:59:01,067: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -timeleft
 output : 689740

 error: 
 retcode : 0
DEBUG 2019-04-05 21:59:01,980: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -actimeleft
 output : 689740

 error: 
 retcode : 0
DEBUG 2019-04-05 21:59:01,981: 	 Proxy valid for 191:35:40 hours
INFO 2019-04-05 21:59:01,981: 	 Will use CRAB configuration file crabConfigTemp.py
DEBUG 2019-04-05 21:59:01,981: 	 Loading CRAB configuration file.
ERROR 2019-04-05 21:59:01,984: 	 Error while loading CRAB configuration:
invalid syntax (crabConfigTemp.py, line 19)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-04-05 21:59:01,985: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
invalid syntax (crabConfigTemp.py, line 19)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-04-05 21:59:02,827: 	 Executing command: 'submit'
DEBUG 2019-04-05 21:59:02,828: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
DEBUG 2019-04-05 21:59:02,838: 	 Checking credentials
DEBUG 2019-04-05 21:59:02,840: 	 Found proxy file /tmp/x509up_u104803
DEBUG 2019-04-05 21:59:02,840: 	 Getting proxy life time left
DEBUG 2019-04-05 21:59:03,752: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -timeleft
 output : 689738

 error: 
 retcode : 0
DEBUG 2019-04-05 21:59:04,559: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -actimeleft
 output : 689737

 error: 
 retcode : 0
DEBUG 2019-04-05 21:59:04,560: 	 Proxy lifetime 689738 secs is different from voms extension lifetime 689737 secs for proxy: /tmp/x509up_u104803
DEBUG 2019-04-05 21:59:04,560: 	 Proxy valid for 191:35:37 hours
INFO 2019-04-05 21:59:04,561: 	 Will use CRAB configuration file crabConfigTemp.py
DEBUG 2019-04-05 21:59:04,561: 	 Loading CRAB configuration file.
ERROR 2019-04-05 21:59:04,565: 	 Error while loading CRAB configuration:
invalid syntax (crabConfigTemp.py, line 19)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2019-04-05 21:59:04,566: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 87, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
invalid syntax (crabConfigTemp.py, line 19)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2019-04-05 21:59:05,369: 	 Executing command: 'submit'
DEBUG 2019-04-05 21:59:05,369: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
DEBUG 2019-04-05 21:59:05,380: 	 Checking credentials
DEBUG 2019-04-05 21:59:05,380: 	 Found proxy file /tmp/x509up_u104803
DEBUG 2019-04-05 21:59:05,380: 	 Getting proxy life time left
DEBUG 2019-04-05 21:59:06,294: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -timeleft
 output : 689735

 error: 
 retcode : 0
ERROR 2019-04-05 21:59:07,187: 	 Keyboard Interrupted
DEBUG 2019-04-11 12:39:34,086: 	 Executing command: 'status'
DEBUG 2019-04-11 12:39:34,087: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
ERROR 2019-04-11 12:39:34,124: 	 Error: crab_monoH_2016DATA_20190411/SingleElectron-Run2016H-03Feb2017_ver3-v1 is not a valid CRAB project directory.
ERROR 2019-04-11 12:39:34,124: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_monoH_2016DATA_20190411/SingleElectron-Run2016H-03Feb2017_ver3-v1 is not a valid CRAB project directory.
DEBUG 2019-04-11 13:18:34,218: 	 Executing command: 'submit'
DEBUG 2019-04-11 13:18:34,218: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
DEBUG 2019-04-11 13:18:34,242: 	 Checking credentials
DEBUG 2019-04-11 13:18:34,243: 	 Found proxy file /tmp/x509up_u104803
DEBUG 2019-04-11 13:18:34,243: 	 Getting proxy life time left
DEBUG 2019-04-11 13:18:35,252: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -timeleft
 output : 689095

 error: 
 retcode : 0
DEBUG 2019-04-11 13:18:36,273: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -actimeleft
 output : 689094

 error: 
 retcode : 0
DEBUG 2019-04-11 13:18:36,274: 	 Proxy lifetime 689095 secs is different from voms extension lifetime 689094 secs for proxy: /tmp/x509up_u104803
DEBUG 2019-04-11 13:18:36,274: 	 Proxy valid for 191:24:54 hours
INFO 2019-04-11 13:18:36,274: 	 Will use CRAB configuration file crabConfigTemp.py
DEBUG 2019-04-11 13:18:36,274: 	 Loading CRAB configuration file.
DEBUG 2019-04-11 13:18:36,297: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-11 13:18:36,332: 	 Unhandled Exception!
ERROR 2019-04-11 13:18:36,332: 	 [Errno 122] Disk quota exceeded: '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016H-03Feb2017_ver2-v1'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 407, in createWorkArea
    os.mkdir(fullpath)
OSError: [Errno 122] Disk quota exceeded: '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016H-03Feb2017_ver2-v1'
ERROR 2019-04-11 13:18:36,341: 	 ERROR: OSError: [Errno 122] Disk quota exceeded: '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016H-03Feb2017_ver2-v1'
ERROR 2019-04-11 13:18:36,342: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2019-04-11 13:18:36,342: 	 	Client Version: 3.3.1903.patch1
ERROR 2019-04-11 13:18:36,342: 	 	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab.log to the CRAB cache.
DEBUG 2019-04-11 13:18:37,402: 	 Executing command: 'submit'
DEBUG 2019-04-11 13:18:37,402: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
DEBUG 2019-04-11 13:18:37,418: 	 Checking credentials
DEBUG 2019-04-11 13:18:37,423: 	 Found proxy file /tmp/x509up_u104803
DEBUG 2019-04-11 13:18:37,423: 	 Getting proxy life time left
DEBUG 2019-04-11 13:18:38,433: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -timeleft
 output : 689092

 error: 
 retcode : 0
DEBUG 2019-04-11 13:18:39,444: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -actimeleft
 output : 689091

 error: 
 retcode : 0
DEBUG 2019-04-11 13:18:39,445: 	 Proxy lifetime 689092 secs is different from voms extension lifetime 689091 secs for proxy: /tmp/x509up_u104803
DEBUG 2019-04-11 13:18:39,445: 	 Proxy valid for 191:24:51 hours
INFO 2019-04-11 13:18:39,445: 	 Will use CRAB configuration file crabConfigTemp.py
DEBUG 2019-04-11 13:18:39,445: 	 Loading CRAB configuration file.
DEBUG 2019-04-11 13:18:39,449: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-11 13:18:39,452: 	 Unhandled Exception!
ERROR 2019-04-11 13:18:39,452: 	 [Errno 122] Disk quota exceeded: '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016H-03Feb2017_ver3-v1'
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 407, in createWorkArea
    os.mkdir(fullpath)
OSError: [Errno 122] Disk quota exceeded: '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016H-03Feb2017_ver3-v1'
ERROR 2019-04-11 13:18:39,460: 	 ERROR: OSError: [Errno 122] Disk quota exceeded: '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016H-03Feb2017_ver3-v1'
ERROR 2019-04-11 13:18:39,460: 	 
	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
ERROR 2019-04-11 13:18:39,460: 	 	Client Version: 3.3.1903.patch1
ERROR 2019-04-11 13:18:39,460: 	 	Please use 'crab uploadlog' to upload the log file /afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab.log to the CRAB cache.
DEBUG 2019-04-11 13:35:48,323: 	 Executing command: 'status'
DEBUG 2019-04-11 13:35:48,323: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
ERROR 2019-04-11 13:35:48,329: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016G-03Feb2017-v1
ERROR 2019-04-11 13:35:48,329: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 590, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 452, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016G-03Feb2017-v1
DEBUG 2019-04-11 13:47:21,295: 	 Executing command: 'submit'
DEBUG 2019-04-11 13:47:21,297: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
DEBUG 2019-04-11 13:47:21,326: 	 Checking credentials
DEBUG 2019-04-11 13:47:21,328: 	 Found proxy file /tmp/x509up_u104803
DEBUG 2019-04-11 13:47:21,328: 	 Getting proxy life time left
DEBUG 2019-04-11 13:47:22,442: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -timeleft
 output : 687368

 error: 
 retcode : 0
DEBUG 2019-04-11 13:47:23,453: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -actimeleft
 output : 687367

 error: 
 retcode : 0
DEBUG 2019-04-11 13:47:23,454: 	 Proxy lifetime 687368 secs is different from voms extension lifetime 687367 secs for proxy: /tmp/x509up_u104803
DEBUG 2019-04-11 13:47:23,454: 	 Proxy valid for 190:56:07 hours
INFO 2019-04-11 13:47:23,455: 	 Will use CRAB configuration file crabConfigTemp.py
DEBUG 2019-04-11 13:47:23,455: 	 Loading CRAB configuration file.
DEBUG 2019-04-11 13:47:23,465: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-11 13:47:23,465: 	 Working area '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016G-03Feb2017-v1' already exists 
Please change the requestName in the config file
ERROR 2019-04-11 13:47:23,466: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016G-03Feb2017-v1' already exists 
Please change the requestName in the config file
DEBUG 2019-04-11 13:53:06,216: 	 Executing command: 'status'
DEBUG 2019-04-11 13:53:06,216: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
ERROR 2019-04-11 13:53:06,217: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016G-03Feb2017-v1
ERROR 2019-04-11 13:53:06,217: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 590, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 452, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016DATA_20190411/crab_MET-Run2016G-03Feb2017-v1
DEBUG 2019-04-11 14:48:09,139: 	 Executing command: 'submit'
DEBUG 2019-04-11 14:48:09,140: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
DEBUG 2019-04-11 14:48:09,159: 	 Checking credentials
DEBUG 2019-04-11 14:48:09,160: 	 Found proxy file /tmp/x509up_u104803
DEBUG 2019-04-11 14:48:09,160: 	 Getting proxy life time left
DEBUG 2019-04-11 14:48:10,586: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -timeleft
 output : 683720

 error: 
 retcode : 0
DEBUG 2019-04-11 14:48:11,808: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u104803 -actimeleft
 output : 683719

 error: 
 retcode : 0
DEBUG 2019-04-11 14:48:11,809: 	 Proxy lifetime 683720 secs is different from voms extension lifetime 683719 secs for proxy: /tmp/x509up_u104803
DEBUG 2019-04-11 14:48:11,809: 	 Proxy valid for 189:55:19 hours
INFO 2019-04-11 14:48:11,809: 	 Will use CRAB configuration file crabConfigTemp.py
DEBUG 2019-04-11 14:48:11,809: 	 Loading CRAB configuration file.
DEBUG 2019-04-11 14:48:11,822: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2019-04-11 14:48:11,823: 	 Working area '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016data_20190411/crab_MET-Run2016G-03Feb2017-v1' already exists 
Please change the requestName in the config file
ERROR 2019-04-11 14:48:11,823: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 315, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 404, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/d/dekumar/public/monoH/DelPanj_2016_test/CMSSW_8_0_26_patch1/src/DelPanj/CrabUtilities/MultiCrab_data/crab_monoH_2016data_20190411/crab_MET-Run2016G-03Feb2017-v1' already exists 
Please change the requestName in the config file
DEBUG 2019-04-11 20:50:30,872: 	 Executing command: 'status'
DEBUG 2019-04-11 20:50:30,872: 	 Found CRAB cache file /afs/cern.ch/user/d/dekumar/.crab3
ERROR 2019-04-11 20:50:30,873: 	 Error: crab_monoH_2016data_20190411/SingleElectron-Run2016B-03Feb2017_ver2-v2/ is not a valid CRAB project directory.
ERROR 2019-04-11 20:50:30,873: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/status.py", line 40, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 268, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1903.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 586, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_monoH_2016data_20190411/SingleElectron-Run2016B-03Feb2017_ver2-v2/ is not a valid CRAB project directory.
